### ISSUE TITLE
error when npm or yarn run dev

### ISSUE THREAD

**Issue by jasnzhuang** [fastapi-practices/fastapi_best_architecture_ui_arco#44]
<img width="858" alt="image" src="https://github.com/fastapi-practices/fastapi_best_architecture_ui/assets/16612921/be6495a0-b290-4c68-8b5f-8652f26eb855">
<img width="862" alt="image" src="https://github.com/fastapi-practices/fastapi_best_architecture_ui/assets/16612921/c6275d9e-c206-4327-9028-bb20544a9854">
```
PS C:\dev\fastapi_best_architecture_ui> yarn run dev
yarn run v1.22.19
$ vite --config ./config/vite.config.dev.ts

  VITE v3.2.7  ready in 1140 ms

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
✘ [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "@intlify/shared" package

    node_modules/vite/node_modules/esbuild/lib/main.js:1336:21:
      1336 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:34107:11)
    at resolvePackageEntry (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:34102:9)
    at tryNodeResolve (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:33842:20)
    at Context.resolveId (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:33602:28)
    at Object.resolveId (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:40539:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:62784:21
    at async file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:34422:34
    at async requestCallbacks.on-resolve (C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:1336:22)
    at async handleRequest (C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:706:13)

  This error came from the "onResolve" callback registered here:

    node_modules/vite/node_modules/esbuild/lib/main.js:1260:20:
      1260 │       let promise = setup({
           ╵                     ^

    at setup (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:34402:19)
    at handlePlugins (C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:1260:21)
    at buildOrServeImpl (C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:951:5)
    at Object.buildOrServe (C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:759:5)
    at C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:2096:17
    at new Promise (<anonymous>)
    at Object.build (C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:2095:14)
    at build (C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:1942:51)
    at runOptimizeDeps (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:41890:26)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/vue-i18n/dist/vue-i18n.cjs:8:21:
      8 │ var shared = require('@intlify/shared');
        ╵                      ~~~~~~~~~~~~~~~~~

C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:1575
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/vite/node_modules/esbuild/lib/main.js:1336:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "@intlify/shared" package
    at failureErrorWithLog (C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:1575:15)
    at C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:1033:28
    at runOnEndCallbacks (C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:1447:61)
    at buildResponseToResult (C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:1031:7)
    at C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:1143:14
    at responseCallbacks.<computed> (C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:680:9)
    at handleIncomingPacket (C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:735:9)
    at Socket.readFromStdout (C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: Error: Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "@intlify/shared" package
          at packageEntryFailure (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:34107:11)
          at resolvePackageEntry (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:34102:9)
          at tryNodeResolve (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:33842:20)
          at Context.resolveId (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:33602:28)
          at Object.resolveId (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:40539:46)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:62784:21
          at async file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:34422:34
          at async requestCallbacks.on-resolve (C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:1336:22)
          at async handleRequest (C:\dev\fastapi_best_architecture_ui\node_modules\vite\node_modules\esbuild\lib\main.js:706:13),
      id: '',
      location: {
        column: 21,
        file: 'node_modules/vite/node_modules/esbuild/lib/main.js',
        length: 0,
        line: 1336,
        lineText: '        let result = await callback({\n' +
          '    at packageEntryFailure (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:34107:11)\n' +
          '    at resolvePackageEntry (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:34102:9)\n' +
          '    at tryNodeResolve (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:33842:20)\n' +
          '    at Context.resolveId (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:33602:28)\n' +
          '    at Object.resolveId (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:40539:46)\n' +
          '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
          '    at async file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:62784:21\n' +
          '    at async file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:34422:34\n' +
          '    at async requestCallbacks.on-resolve (C:\\dev\\fastapi_best_architecture_ui\\node_modules\\vite\\node_modules\\esbuild\\lib\\main.js:1336:22)\n' +
          '    at async handleRequest (C:\\dev\\fastapi_best_architecture_ui\\node_modules\\vite\\node_modules\\esbuild\\lib\\main.js:706:13)',
        namespace: 'file',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 20,
            file: 'node_modules/vite/node_modules/esbuild/lib/main.js',
            length: 0,
            line: 1260,
            lineText: '      let promise = setup({\n' +
              '    at setup (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:34402:19)\n' +
              '    at handlePlugins (C:\\dev\\fastapi_best_architecture_ui\\node_modules\\vite\\node_modules\\esbuild\\lib\\main.js:1260:21)\n' +
              '    at buildOrServeImpl (C:\\dev\\fastapi_best_architecture_ui\\node_modules\\vite\\node_modules\\esbuild\\lib\\main.js:951:5)\n' +
              '    at Object.buildOrServe (C:\\dev\\fastapi_best_architecture_ui\\node_modules\\vite\\node_modules\\esbuild\\lib\\main.js:759:5)\n' +
              '    at C:\\dev\\fastapi_best_architecture_ui\\node_modules\\vite\\node_modules\\esbuild\\lib\\main.js:2096:17\n' +
              '    at new Promise (<anonymous>)\n' +
              '    at Object.build (C:\\dev\\fastapi_best_architecture_ui\\node_modules\\vite\\node_modules\\esbuild\\lib\\main.js:2095:14)\n' +
              '    at build (C:\\dev\\fastapi_best_architecture_ui\\node_modules\\vite\\node_modules\\esbuild\\lib\\main.js:1942:51)\n' +
              '    at runOptimizeDeps (file:///C:/dev/fastapi_best_architecture_ui/node_modules/vite/dist/node/chunks/dep-2faf2534.js:41890:26)',
            namespace: 'file',
            suggestion: ''
          },
          text: 'This error came from the "onResolve" callback registered here:'
        },
        {
          location: {
            column: 21,
            file: 'node_modules/vue-i18n/dist/vue-i18n.cjs',
            length: 17,
            line: 8,
            lineText: "var shared = require('@intlify/shared');",
            namespace: '',
            suggestion: ''
          },
          text: 'The plugin "vite:dep-pre-bundle" was triggered by this import'
        }
      ],
      pluginName: 'vite:dep-pre-bundle',
      text: 'Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "@intlify/shared" package'
    }
  ],
  warnings: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jasnzhuang** [comment]
I tried to change the version of "vue-i18n" in package.json file to "9.2.2" and solved the problem, just for reference

**Comment by wu-clan** [comment]
Due to possible compatibility issues with some package upgrades, I've created a [PR](#45) to upload the yarn.lock file, thanks for bringing it up!

**Comment by wu-clan** [comment]
Due to possible compatibility issues with some package upgrades, I've created a #45 to upload the yarn.lock file, thanks for bringing it up!
